# Generated by Django 5.2 on 2025-05-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Archive",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titulo", models.CharField(max_length=200)),
                ("arquivo", models.FileField(storage="minio_storage.storage.MinioMediaStorage", upload_to="")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
