[project]
name = "FabricaMinio"
version = "0.1.0"
description = "An example of how to use minio"
authors = [
    {name = "jonatasperaza", email = "jonatassilvaperaza@gmail.com"},
]
dependencies = ["django>=5.2", "minio>=7.2.15", "python-dotenv>=1.1.0", "djangorestframework>=3.16.0", "django-minio-storage>=0.5.7"]
requires-python = ">=3.13"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[[tool.pdm.autoexport]]
filename = "requirements.txt"
without-hashes = "true"

[tool.black]
line-length = 150

[tool.pdm]
distribution = true

[tool.pdm.scripts]
dev = "python manage.py runserver"
runserver = "python manage.py runserver"
createsuperuser = "python manage.py createsuperuser"
migrate = "python manage.py migrate"
makemigrations = "python manage.py makemigrations"
shell = "python manage.py shell"
test = "python manage.py test"
startapp = "python manage.py startapp {args}"
loaddata = "python manage.py loaddata {args}"
dumpdata = "python manage.py dumpdata {args}"
[dependency-groups]
dev = [
    "isort>=6.0.1",
    "black>=25.1.0",
]
